### ISSUE TITLE
EDA cleanup: Remove AllClinEpiDB project from model XML when client is ready

### ISSUE THREAD

**Issue by ryanrdoherty** [VEuPathDB/ClinEpiWebsite#21]
Will require edits to these files, I believe:
```
ClinEpiWebsite/Model/lib/conifer/roles/conifer/vars/ClinEpi/default.yml
ClinEpiWebsite/Model/lib/conifer/roles/conifer/vars/ClinEpi/production/default.yml
```
Depends on completion of client work detailed here: https://github.com/VEuPathDB/web-eda/issues/822

**Comment by aurreco-uga** [comment]
done

some stuff remains in ClinEpiModel but that is on DD
[aurreco@durian project_home]$ grep -rl "AllClinEpiDB" ClinEpiModel/Model/lib/wdk/model/*
ClinEpiModel/Model/lib/wdk/model/questions/participantQuestions.xml
ClinEpiModel/Model/lib/wdk/model/records/xmlRecords.xml

**Comment by danicahelb** [comment]
@ryanrdoherty @aurreco-uga is there anything we should QA here?

**Comment by ryanrdoherty** [comment]
> @ryanrdoherty @aurreco-uga is there anything we should QA here?

The QA would be to make sure the correct studies show up on regular qa vs qa.restricted.

**Comment by nkittur-uga** [comment]
Confirmed that the correct studies are showing up on qa.clinepi vs. qa.restricted.
