### ISSUE TITLE
Remove "Find Studies" search box from ClinEpi home page

### ISSUE THREAD

**Issue by nkittur-uga** [VEuPathDB/ClinEpiWebsite#46]
The new Site Search feature has now been implemented, with a new search box in the header. The "Find Studies" search box lower down on the ClinEpi home page should be removed. 
<img width="1420" alt="Screen Shot 2022-06-07 at 12 40 19 PM" src="https://user-images.githubusercontent.com/67710160/172437033-a88e759c-7edc-497f-8aec-074b0be1a869.png">

**Comment by danicahelb** [comment]
looks good


![Image](https://user-images.githubusercontent.com/25450900/172704993-3bb0b49b-1d05-4d87-b4ed-f80f6682117c.png)
