### ISSUE TITLE
DIY epi styling / verbiage changes

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/ClinEpiWebsite#47]
Discussed in 6/17/2022 EDA UX meeting

Terminology to differentiate official studies from DIY studies:
- DIY datasets will use the terminology: “User studies”
- ClinEpi studies will use the terminology: “Curated studies”

**Changes needed:**

_On the “Study summaries” page:_
- Page header should be: `Study summaries`
- Add a sub-header for `User studies`
- Add a sub-header for `Curated studies`

_On the “My studies” summary page:_
- Page header should be: `My user studies`

_On the “My studies” page for a particular user dataset:_
- Page header should be: `My user studies: _My user study name_ `(“My user study name” should be in italics, because every time text is editable (like “Analysis name”) it appears in italics)
- Change `Use This Dataset in ClinEpiDB` sub-header to `Explore in ClinEpiDB` (Explore in ClinEpiDB will be a link that takes you to an analysis page for this user study in the EDA)
- Remove hyperlinked study name under `Use This Dataset in ClinEpiDB`

_On the dropdown menu:_
Change `Workspace > My studies` to `Workspace > My User Studies`

**Comment by SheenaTomko** [comment]
All changes were made
