### ISSUE TITLE
Website: Studies menu filter foiled by italic species names

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/ClinEpiWebsite#48]
If I want to find "SCORE S. mansoni" by typing into the filter in the Clinepi website's Studies menu, it won't work if I type `SCORE S`.

I have to type `SCORE <` because I happen to know there is an italic `<i>` tag in the study name.

Filtering should strip HTML first.

Pretty sure this is NOT a `web-eda` ticket - probably website related (don't know which repo).  @jtlong3rd or @dmfalke can advise.

Cost is low though.

**Comment by sweverschulman** [comment]
The Italicized species name no longer foils the studies drop down menu.  

<img width="426" alt="Screen Shot 2022-07-12 at 1 45 38 PM" src="https://user-images.githubusercontent.com/62298921/178558799-15422f74-2a45-4d3c-bda0-ef5186b886b1.png">
