### ISSUE TITLE
Site Search: Update column names for eda-specific document types

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/ClinEpiWebsite#49]
_Originally reported in https://github.com/VEuPathDB/SiteSearchData/issues/6#issue-1278936424_

---

In the tables for "Variables having this value" and "Study specific variable information", there is a column called "Study". Please rename this to "Study name" in both tables so that the terminology is used consistently 

<img width="445" alt="image" src="https://user-images.githubusercontent.com/25450900/174188806-17cb253a-97cd-4133-a551-7cd60e8fc33b.png">

<img width="420" alt="image" src="https://user-images.githubusercontent.com/25450900/174188873-a7aed5ce-cda2-4e71-9022-c3e4688ab493.png">

**Comment by nkittur-uga** [comment]
Has been renamed to "Study name" in both tables. QA is complete.
