### ISSUE TITLE
Bug: Unreleased studies accessible on live site

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB/ClinEpiWebsite#60]
Nupur created a link for an unreleased study (https://clinepidb.org/ce/app/workspace/analyses/DS_0605f599e5) that the provider could put in a manuscript for when the study is released. However, the link not only works, but a guest can start an analysis from this. Ideally, a link like this should give a page not found error until the study is released

**Comment by dmfalke** [comment]
Part of the solution for this involves checking website configuration (`showUnreleasedData`) this is currently not passed to the eda codebase, so it will take a little bit of time figuring out the best way to approach this.

**Comment by danicahelb** [comment]
hey @dmfalke is this something you think could get fixed soon (ie, b60)?

**Comment by dmfalke** [comment]
This resolution of this issue depends on fixes from:
- https://github.com/VEuPathDB/EbrcWebsiteCommon/commit/9e97614952f5119546ec05e0d8e12a5b8552cdc6
- https://github.com/VEuPathDB/web-eda/tree/handle-unreleased-data

I plan to patch the live site, once everything has been merged and published to npm.

**Comment by SheenaTomko** [comment]
@dmfalke the link from the original ticket still works for me and I can still open an analysis from it. Is this because the study is protected rather than private?

**Comment by dmfalke** [comment]
Sorry, I moved this to "Ready for testing" prematurely. The live site doesn't have the change, yet.

**Comment by SheenaTomko** [comment]
Looks good now. Thanks Dave! Marking as complete
