### ISSUE TITLE
Make tabs "sticky"

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/ClinEpiWebsite#72]
when the user scrolls down a page, for example the Study details tab, the tabs should always remain visible instead of scrolling out of view. We want the user to be able to "save their place" on the study details tab (for ex, a description of the study arms) so they can come back and refer to it as they are working on their analysis.

currently, the tabs scroll out of view so the user must navigate away from their position on the study details tab in order to navigate to the B&S tab

**Comment by dmfalke** [comment]
After some investigation, we already has an override in place, but it was being applied in the wrong order. The "quick" solution is to add `!important` to the CSS rule. I think it's okay, in this case.

**Comment by SheenaTomko** [comment]
The tabs now always stay at the top of the page. 
Still have an issue if you scroll down the study details page, navigate to another tab, and come back you start at the top of the study details page again, but it is easier to navigate across pages. 

If we really think saving the spot on the study details tab is important we can make another ticket for that, but I am going to consider this closed @danicahelb

**Comment by danicahelb** [comment]
made this ticket: https://github.com/VEuPathDB/EdaNewIssues/issues/540
it is not a priority for implementation at this point
